apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: ttubeot-adventure
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: ttubeot-adventure
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
