apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-tls
  namespace: ttubeot-user
spec:
  secretName: letsencrypt-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: ssafy.picel.net
  dnsNames:
  - ssafy.picel.net